/********************************************************************************
** Form generated from reading UI file 'recipe.ui'
**
** Created by: Qt User Interface Compiler version 5.2.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_RECIPE_H
#define UI_RECIPE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>

QT_BEGIN_NAMESPACE

class Ui_dialRecipe
{
public:
    QDialogButtonBox *buttonBox;
    QGroupBox *grpSteps;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_10;
    QFrame *line_11;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_51;
    QFrame *line_9;
    QFrame *line_12;
    QFrame *line_13;
    QLabel *label_52;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *fraLeftBIB;
    QLabel *label;
    QLabel *label_10;
    QSpinBox *spinBox;
    QLabel *lblLBIB_RTDVol;
    QLabel *label_12;
    QSpinBox *spinBox_2;
    QLabel *label_13;
    QSpinBox *spinBox_3;
    QLabel *label_14;
    QSpinBox *spinBox_4;
    QLabel *label_15;
    QComboBox *cboDefSize_2;
    QLabel *label_11;
    QDoubleSpinBox *doubleSpinBox;
    QLabel *label_16;
    QSpinBox *spinBox_5;
    QLabel *label_17;
    QSpinBox *spinBox_6;
    QLabel *lblLBIBPulsesMild;
    QLabel *lblLBIBPulsesNormal;
    QLabel *lblLBIBPulsesStrong;
    QLabel *label_18;
    QSlider *horizontalSlider;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QSpinBox *spinBox_7;
    QLabel *label_22;
    QSpinBox *spinBox_8;
    QLabel *label_23;
    QSlider *horizontalSlider_2;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QFrame *fraGeneral;
    QLabel *lblDeAirTime;
    QLabel *lblDeAirTimeValue;
    QLabel *label_2;
    QSpinBox *spPrTime;
    QLabel *label_3;
    QSpinBox *spRTDLarge;
    QSpinBox *spRTDLarge_2;
    QLabel *label_4;
    QSpinBox *spRTDLarge_3;
    QLabel *label_5;
    QLabel *label_6;
    QComboBox *cboSeq1;
    QLabel *label_7;
    QComboBox *cboSeq2;
    QLabel *label_8;
    QComboBox *cboSeq3;
    QLabel *label_9;
    QComboBox *cboDefSize;
    QPushButton *btnChange;
    QFrame *fraLeftBIB_2;
    QLabel *label_32;
    QLabel *label_33;
    QSpinBox *spinBox_9;
    QLabel *lblLBIB_RTDVol_2;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QComboBox *cboDefSize_3;
    QLabel *label_38;
    QDoubleSpinBox *doubleSpinBox_2;
    QLabel *label_39;
    QSpinBox *spinBox_13;
    QLabel *label_40;
    QSpinBox *spinBox_14;
    QLabel *lblLBIBPulsesMild_2;
    QLabel *lblLBIBPulsesNormal_2;
    QLabel *lblLBIBPulsesStrong_2;
    QLabel *label_41;
    QSlider *horizontalSlider_3;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_49;
    QLabel *label_50;
    QDoubleSpinBox *doubleSpinBox_3;
    QDoubleSpinBox *doubleSpinBox_4;
    QDoubleSpinBox *doubleSpinBox_5;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QSpinBox *spinBox_11;
    QSlider *horizontalSlider_4;
    QSpinBox *spinBox_12;
    QLabel *label_47;
    QLabel *label_48;
    QFrame *fraLeftBIB_3;
    QLabel *label_53;
    QLabel *label_54;
    QSpinBox *spinBox_10;
    QLabel *lblLBIB_RTDVol_3;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QComboBox *cboDefSize_4;
    QLabel *label_59;
    QDoubleSpinBox *doubleSpinBox_6;
    QLabel *label_60;
    QSpinBox *spinBox_17;
    QLabel *label_61;
    QSpinBox *spinBox_18;
    QLabel *lblLBIBPulsesMild_3;
    QLabel *lblLBIBPulsesNormal_3;
    QLabel *lblLBIBPulsesStrong_3;
    QLabel *label_70;
    QLabel *label_71;
    QDoubleSpinBox *doubleSpinBox_7;
    QDoubleSpinBox *doubleSpinBox_8;
    QDoubleSpinBox *doubleSpinBox_9;
    QSpinBox *spinBox_19;
    QLabel *label_69;
    QSpinBox *spinBox_20;
    QLabel *label_66;
    QLabel *label_65;
    QLabel *label_67;
    QLabel *label_68;
    QSlider *horizontalSlider_6;
    QSpinBox *spinBox_21;
    QLabel *label_74;
    QLabel *label_75;
    QSpinBox *spinBox_22;
    QGroupBox *groupBox;
    QLabel *label_72;
    QComboBox *comboBox;
    QLabel *label_73;
    QComboBox *comboBox_2;
    QPushButton *pushButton;

    void setupUi(QDialog *dialRecipe)
    {
        if (dialRecipe->objectName().isEmpty())
            dialRecipe->setObjectName(QStringLiteral("dialRecipe"));
        dialRecipe->resize(1288, 801);
        buttonBox = new QDialogButtonBox(dialRecipe);
        buttonBox->setObjectName(QStringLiteral("buttonBox"));
        buttonBox->setGeometry(QRect(920, 750, 341, 32));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        grpSteps = new QGroupBox(dialRecipe);
        grpSteps->setObjectName(QStringLiteral("grpSteps"));
        grpSteps->setGeometry(QRect(10, 500, 1061, 291));
        line = new QFrame(grpSteps);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(10, 260, 1031, 20));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(grpSteps);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(0, 40, 21, 241));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(grpSteps);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(40, 40, 31, 51));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(grpSteps);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(90, 40, 21, 71));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(grpSteps);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(290, 40, 21, 71));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(grpSteps);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(1030, 30, 21, 251));
        line_11->setFrameShape(QFrame::VLine);
        line_11->setFrameShadow(QFrame::Sunken);
        label_28 = new QLabel(grpSteps);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(10, 20, 16, 16));
        label_29 = new QLabel(grpSteps);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 50, 16, 16));
        label_30 = new QLabel(grpSteps);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(80, 120, 46, 41));
        label_31 = new QLabel(grpSteps);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(280, 120, 46, 41));
        label_51 = new QLabel(grpSteps);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(320, 120, 41, 31));
        line_9 = new QFrame(grpSteps);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(100, 70, 201, 20));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(grpSteps);
        line_12->setObjectName(QStringLiteral("line_12"));
        line_12->setGeometry(QRect(50, 50, 51, 20));
        line_12->setFrameShape(QFrame::HLine);
        line_12->setFrameShadow(QFrame::Sunken);
        line_13 = new QFrame(grpSteps);
        line_13->setObjectName(QStringLiteral("line_13"));
        line_13->setGeometry(QRect(10, 40, 41, 20));
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        label_52 = new QLabel(grpSteps);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(70, 60, 16, 16));
        line_14 = new QFrame(grpSteps);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(300, 60, 41, 16));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(grpSteps);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(333, 40, 20, 71));
        line_15->setFrameShape(QFrame::VLine);
        line_15->setFrameShadow(QFrame::Sunken);
        fraLeftBIB = new QFrame(dialRecipe);
        fraLeftBIB->setObjectName(QStringLiteral("fraLeftBIB"));
        fraLeftBIB->setGeometry(QRect(270, 10, 331, 471));
        fraLeftBIB->setFrameShape(QFrame::StyledPanel);
        fraLeftBIB->setFrameShadow(QFrame::Raised);
        label = new QLabel(fraLeftBIB);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 10, 91, 21));
        label_10 = new QLabel(fraLeftBIB);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 50, 101, 21));
        spinBox = new QSpinBox(fraLeftBIB);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(130, 50, 61, 22));
        spinBox->setMaximum(100);
        spinBox->setValue(100);
        lblLBIB_RTDVol = new QLabel(fraLeftBIB);
        lblLBIB_RTDVol->setObjectName(QStringLiteral("lblLBIB_RTDVol"));
        lblLBIB_RTDVol->setGeometry(QRect(200, 50, 61, 21));
        label_12 = new QLabel(fraLeftBIB);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 90, 71, 20));
        spinBox_2 = new QSpinBox(fraLeftBIB);
        spinBox_2->setObjectName(QStringLiteral("spinBox_2"));
        spinBox_2->setGeometry(QRect(130, 90, 61, 22));
        spinBox_2->setValue(23);
        label_13 = new QLabel(fraLeftBIB);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 110, 91, 20));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_13->setFont(font);
        spinBox_3 = new QSpinBox(fraLeftBIB);
        spinBox_3->setObjectName(QStringLiteral("spinBox_3"));
        spinBox_3->setGeometry(QRect(130, 110, 61, 22));
        spinBox_3->setFont(font);
        spinBox_3->setValue(23);
        label_14 = new QLabel(fraLeftBIB);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 130, 81, 20));
        spinBox_4 = new QSpinBox(fraLeftBIB);
        spinBox_4->setObjectName(QStringLiteral("spinBox_4"));
        spinBox_4->setGeometry(QRect(130, 130, 61, 22));
        spinBox_4->setValue(23);
        label_15 = new QLabel(fraLeftBIB);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 160, 101, 21));
        cboDefSize_2 = new QComboBox(fraLeftBIB);
        cboDefSize_2->setObjectName(QStringLiteral("cboDefSize_2"));
        cboDefSize_2->setGeometry(QRect(130, 160, 71, 22));
        label_11 = new QLabel(fraLeftBIB);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 200, 91, 21));
        doubleSpinBox = new QDoubleSpinBox(fraLeftBIB);
        doubleSpinBox->setObjectName(QStringLiteral("doubleSpinBox"));
        doubleSpinBox->setGeometry(QRect(130, 200, 71, 22));
        doubleSpinBox->setDecimals(1);
        doubleSpinBox->setMaximum(20);
        doubleSpinBox->setSingleStep(0.5);
        doubleSpinBox->setValue(10);
        label_16 = new QLabel(fraLeftBIB);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 240, 111, 21));
        spinBox_5 = new QSpinBox(fraLeftBIB);
        spinBox_5->setObjectName(QStringLiteral("spinBox_5"));
        spinBox_5->setGeometry(QRect(130, 240, 71, 22));
        label_17 = new QLabel(fraLeftBIB);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 260, 111, 21));
        spinBox_6 = new QSpinBox(fraLeftBIB);
        spinBox_6->setObjectName(QStringLiteral("spinBox_6"));
        spinBox_6->setGeometry(QRect(130, 260, 71, 22));
        lblLBIBPulsesMild = new QLabel(fraLeftBIB);
        lblLBIBPulsesMild->setObjectName(QStringLiteral("lblLBIBPulsesMild"));
        lblLBIBPulsesMild->setGeometry(QRect(200, 90, 121, 21));
        lblLBIBPulsesNormal = new QLabel(fraLeftBIB);
        lblLBIBPulsesNormal->setObjectName(QStringLiteral("lblLBIBPulsesNormal"));
        lblLBIBPulsesNormal->setGeometry(QRect(200, 110, 121, 21));
        lblLBIBPulsesNormal->setFont(font);
        lblLBIBPulsesStrong = new QLabel(fraLeftBIB);
        lblLBIBPulsesStrong->setObjectName(QStringLiteral("lblLBIBPulsesStrong"));
        lblLBIBPulsesStrong->setGeometry(QRect(200, 130, 121, 21));
        label_18 = new QLabel(fraLeftBIB);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 320, 46, 13));
        horizontalSlider = new QSlider(fraLeftBIB);
        horizontalSlider->setObjectName(QStringLiteral("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(130, 320, 191, 19));
        horizontalSlider->setMaximum(100);
        horizontalSlider->setSliderPosition(0);
        horizontalSlider->setOrientation(Qt::Horizontal);
        label_19 = new QLabel(fraLeftBIB);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(110, 300, 61, 16));
        label_20 = new QLabel(fraLeftBIB);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(270, 300, 61, 20));
        label_21 = new QLabel(fraLeftBIB);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 410, 111, 21));
        spinBox_7 = new QSpinBox(fraLeftBIB);
        spinBox_7->setObjectName(QStringLiteral("spinBox_7"));
        spinBox_7->setGeometry(QRect(130, 410, 71, 22));
        spinBox_7->setMinimum(-5000);
        spinBox_7->setMaximum(5000);
        spinBox_7->setSingleStep(100);
        label_22 = new QLabel(fraLeftBIB);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 430, 101, 16));
        spinBox_8 = new QSpinBox(fraLeftBIB);
        spinBox_8->setObjectName(QStringLiteral("spinBox_8"));
        spinBox_8->setGeometry(QRect(130, 430, 71, 22));
        spinBox_8->setMaximum(9900);
        spinBox_8->setSingleStep(100);
        spinBox_8->setValue(2500);
        label_23 = new QLabel(fraLeftBIB);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 380, 91, 16));
        horizontalSlider_2 = new QSlider(fraLeftBIB);
        horizontalSlider_2->setObjectName(QStringLiteral("horizontalSlider_2"));
        horizontalSlider_2->setGeometry(QRect(130, 380, 191, 20));
        horizontalSlider_2->setMinimum(40);
        horizontalSlider_2->setMaximum(100);
        horizontalSlider_2->setOrientation(Qt::Horizontal);
        label_24 = new QLabel(fraLeftBIB);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(120, 360, 61, 16));
        label_25 = new QLabel(fraLeftBIB);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(300, 360, 31, 16));
        label_26 = new QLabel(fraLeftBIB);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(130, 10, 46, 21));
        label_26->setFont(font);
        label_27 = new QLabel(fraLeftBIB);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(210, 200, 111, 21));
        fraGeneral = new QFrame(dialRecipe);
        fraGeneral->setObjectName(QStringLiteral("fraGeneral"));
        fraGeneral->setGeometry(QRect(10, 10, 251, 471));
        fraGeneral->setFrameShape(QFrame::StyledPanel);
        fraGeneral->setFrameShadow(QFrame::Raised);
        lblDeAirTime = new QLabel(fraGeneral);
        lblDeAirTime->setObjectName(QStringLiteral("lblDeAirTime"));
        lblDeAirTime->setGeometry(QRect(10, 30, 91, 21));
        lblDeAirTimeValue = new QLabel(fraGeneral);
        lblDeAirTimeValue->setObjectName(QStringLiteral("lblDeAirTimeValue"));
        lblDeAirTimeValue->setGeometry(QRect(130, 30, 46, 21));
        label_2 = new QLabel(fraGeneral);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 60, 91, 21));
        spPrTime = new QSpinBox(fraGeneral);
        spPrTime->setObjectName(QStringLiteral("spPrTime"));
        spPrTime->setGeometry(QRect(130, 60, 111, 22));
        spPrTime->setMaximum(3000);
        spPrTime->setSingleStep(100);
        label_3 = new QLabel(fraGeneral);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 90, 131, 20));
        spRTDLarge = new QSpinBox(fraGeneral);
        spRTDLarge->setObjectName(QStringLiteral("spRTDLarge"));
        spRTDLarge->setGeometry(QRect(130, 90, 111, 22));
        spRTDLarge->setMaximum(10000);
        spRTDLarge->setSingleStep(10);
        spRTDLarge_2 = new QSpinBox(fraGeneral);
        spRTDLarge_2->setObjectName(QStringLiteral("spRTDLarge_2"));
        spRTDLarge_2->setGeometry(QRect(130, 110, 111, 22));
        spRTDLarge_2->setFont(font);
        spRTDLarge_2->setMaximum(10000);
        spRTDLarge_2->setSingleStep(10);
        label_4 = new QLabel(fraGeneral);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 110, 121, 20));
        label_4->setFont(font);
        spRTDLarge_3 = new QSpinBox(fraGeneral);
        spRTDLarge_3->setObjectName(QStringLiteral("spRTDLarge_3"));
        spRTDLarge_3->setGeometry(QRect(130, 130, 111, 22));
        spRTDLarge_3->setMaximum(10000);
        spRTDLarge_3->setSingleStep(10);
        label_5 = new QLabel(fraGeneral);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 130, 111, 20));
        label_6 = new QLabel(fraGeneral);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 310, 191, 21));
        cboSeq1 = new QComboBox(fraGeneral);
        cboSeq1->setObjectName(QStringLiteral("cboSeq1"));
        cboSeq1->setGeometry(QRect(130, 310, 111, 22));
        label_7 = new QLabel(fraGeneral);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 340, 191, 21));
        cboSeq2 = new QComboBox(fraGeneral);
        cboSeq2->setObjectName(QStringLiteral("cboSeq2"));
        cboSeq2->setGeometry(QRect(130, 340, 111, 22));
        label_8 = new QLabel(fraGeneral);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 370, 191, 21));
        cboSeq3 = new QComboBox(fraGeneral);
        cboSeq3->setObjectName(QStringLiteral("cboSeq3"));
        cboSeq3->setGeometry(QRect(130, 370, 111, 22));
        label_9 = new QLabel(fraGeneral);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 160, 101, 21));
        cboDefSize = new QComboBox(fraGeneral);
        cboDefSize->setObjectName(QStringLiteral("cboDefSize"));
        cboDefSize->setGeometry(QRect(130, 160, 111, 22));
        btnChange = new QPushButton(fraGeneral);
        btnChange->setObjectName(QStringLiteral("btnChange"));
        btnChange->setGeometry(QRect(190, 30, 51, 23));
        fraLeftBIB_2 = new QFrame(dialRecipe);
        fraLeftBIB_2->setObjectName(QStringLiteral("fraLeftBIB_2"));
        fraLeftBIB_2->setGeometry(QRect(610, 10, 331, 471));
        fraLeftBIB_2->setFrameShape(QFrame::StyledPanel);
        fraLeftBIB_2->setFrameShadow(QFrame::Raised);
        label_32 = new QLabel(fraLeftBIB_2);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(10, 10, 91, 21));
        label_33 = new QLabel(fraLeftBIB_2);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 50, 101, 21));
        spinBox_9 = new QSpinBox(fraLeftBIB_2);
        spinBox_9->setObjectName(QStringLiteral("spinBox_9"));
        spinBox_9->setGeometry(QRect(130, 50, 61, 22));
        spinBox_9->setMaximum(100);
        spinBox_9->setValue(100);
        lblLBIB_RTDVol_2 = new QLabel(fraLeftBIB_2);
        lblLBIB_RTDVol_2->setObjectName(QStringLiteral("lblLBIB_RTDVol_2"));
        lblLBIB_RTDVol_2->setGeometry(QRect(200, 50, 61, 21));
        label_34 = new QLabel(fraLeftBIB_2);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 90, 71, 20));
        label_35 = new QLabel(fraLeftBIB_2);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 110, 91, 20));
        label_35->setFont(font);
        label_36 = new QLabel(fraLeftBIB_2);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 130, 81, 20));
        label_37 = new QLabel(fraLeftBIB_2);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 160, 101, 21));
        cboDefSize_3 = new QComboBox(fraLeftBIB_2);
        cboDefSize_3->setObjectName(QStringLiteral("cboDefSize_3"));
        cboDefSize_3->setGeometry(QRect(130, 160, 71, 22));
        label_38 = new QLabel(fraLeftBIB_2);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(10, 200, 91, 21));
        doubleSpinBox_2 = new QDoubleSpinBox(fraLeftBIB_2);
        doubleSpinBox_2->setObjectName(QStringLiteral("doubleSpinBox_2"));
        doubleSpinBox_2->setGeometry(QRect(130, 200, 71, 22));
        doubleSpinBox_2->setDecimals(1);
        doubleSpinBox_2->setMaximum(20);
        doubleSpinBox_2->setSingleStep(0.5);
        doubleSpinBox_2->setValue(10);
        label_39 = new QLabel(fraLeftBIB_2);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(10, 240, 111, 21));
        spinBox_13 = new QSpinBox(fraLeftBIB_2);
        spinBox_13->setObjectName(QStringLiteral("spinBox_13"));
        spinBox_13->setGeometry(QRect(130, 240, 71, 22));
        label_40 = new QLabel(fraLeftBIB_2);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(10, 260, 111, 21));
        spinBox_14 = new QSpinBox(fraLeftBIB_2);
        spinBox_14->setObjectName(QStringLiteral("spinBox_14"));
        spinBox_14->setGeometry(QRect(130, 260, 71, 22));
        lblLBIBPulsesMild_2 = new QLabel(fraLeftBIB_2);
        lblLBIBPulsesMild_2->setObjectName(QStringLiteral("lblLBIBPulsesMild_2"));
        lblLBIBPulsesMild_2->setGeometry(QRect(200, 90, 121, 21));
        lblLBIBPulsesNormal_2 = new QLabel(fraLeftBIB_2);
        lblLBIBPulsesNormal_2->setObjectName(QStringLiteral("lblLBIBPulsesNormal_2"));
        lblLBIBPulsesNormal_2->setGeometry(QRect(200, 110, 121, 21));
        lblLBIBPulsesNormal_2->setFont(font);
        lblLBIBPulsesStrong_2 = new QLabel(fraLeftBIB_2);
        lblLBIBPulsesStrong_2->setObjectName(QStringLiteral("lblLBIBPulsesStrong_2"));
        lblLBIBPulsesStrong_2->setGeometry(QRect(200, 130, 121, 21));
        label_41 = new QLabel(fraLeftBIB_2);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(10, 320, 46, 13));
        horizontalSlider_3 = new QSlider(fraLeftBIB_2);
        horizontalSlider_3->setObjectName(QStringLiteral("horizontalSlider_3"));
        horizontalSlider_3->setGeometry(QRect(130, 320, 191, 19));
        horizontalSlider_3->setMaximum(100);
        horizontalSlider_3->setSliderPosition(0);
        horizontalSlider_3->setOrientation(Qt::Horizontal);
        label_42 = new QLabel(fraLeftBIB_2);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(110, 300, 61, 16));
        label_43 = new QLabel(fraLeftBIB_2);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(270, 300, 61, 20));
        label_49 = new QLabel(fraLeftBIB_2);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(130, 10, 46, 21));
        label_49->setFont(font);
        label_50 = new QLabel(fraLeftBIB_2);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(210, 200, 111, 21));
        doubleSpinBox_3 = new QDoubleSpinBox(fraLeftBIB_2);
        doubleSpinBox_3->setObjectName(QStringLiteral("doubleSpinBox_3"));
        doubleSpinBox_3->setGeometry(QRect(130, 90, 62, 22));
        doubleSpinBox_3->setDecimals(1);
        doubleSpinBox_3->setValue(2.2);
        doubleSpinBox_4 = new QDoubleSpinBox(fraLeftBIB_2);
        doubleSpinBox_4->setObjectName(QStringLiteral("doubleSpinBox_4"));
        doubleSpinBox_4->setGeometry(QRect(130, 110, 62, 22));
        doubleSpinBox_4->setDecimals(1);
        doubleSpinBox_4->setValue(2.6);
        doubleSpinBox_5 = new QDoubleSpinBox(fraLeftBIB_2);
        doubleSpinBox_5->setObjectName(QStringLiteral("doubleSpinBox_5"));
        doubleSpinBox_5->setGeometry(QRect(130, 130, 62, 22));
        doubleSpinBox_5->setDecimals(1);
        doubleSpinBox_5->setSingleStep(0.1);
        doubleSpinBox_5->setValue(3);
        label_44 = new QLabel(fraLeftBIB_2);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(300, 360, 31, 16));
        label_45 = new QLabel(fraLeftBIB_2);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(10, 430, 101, 16));
        label_46 = new QLabel(fraLeftBIB_2);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(120, 360, 61, 16));
        spinBox_11 = new QSpinBox(fraLeftBIB_2);
        spinBox_11->setObjectName(QStringLiteral("spinBox_11"));
        spinBox_11->setGeometry(QRect(130, 430, 71, 22));
        spinBox_11->setMaximum(9900);
        spinBox_11->setSingleStep(100);
        spinBox_11->setValue(2500);
        horizontalSlider_4 = new QSlider(fraLeftBIB_2);
        horizontalSlider_4->setObjectName(QStringLiteral("horizontalSlider_4"));
        horizontalSlider_4->setGeometry(QRect(130, 380, 191, 20));
        horizontalSlider_4->setMinimum(40);
        horizontalSlider_4->setMaximum(100);
        horizontalSlider_4->setOrientation(Qt::Horizontal);
        spinBox_12 = new QSpinBox(fraLeftBIB_2);
        spinBox_12->setObjectName(QStringLiteral("spinBox_12"));
        spinBox_12->setGeometry(QRect(130, 410, 71, 22));
        spinBox_12->setMinimum(-5000);
        spinBox_12->setMaximum(5000);
        spinBox_12->setSingleStep(100);
        label_47 = new QLabel(fraLeftBIB_2);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(10, 380, 91, 16));
        label_48 = new QLabel(fraLeftBIB_2);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(10, 410, 111, 21));
        fraLeftBIB_3 = new QFrame(dialRecipe);
        fraLeftBIB_3->setObjectName(QStringLiteral("fraLeftBIB_3"));
        fraLeftBIB_3->setGeometry(QRect(950, 10, 331, 471));
        fraLeftBIB_3->setFrameShape(QFrame::StyledPanel);
        fraLeftBIB_3->setFrameShadow(QFrame::Raised);
        label_53 = new QLabel(fraLeftBIB_3);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(10, 10, 91, 21));
        label_54 = new QLabel(fraLeftBIB_3);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(10, 50, 101, 21));
        spinBox_10 = new QSpinBox(fraLeftBIB_3);
        spinBox_10->setObjectName(QStringLiteral("spinBox_10"));
        spinBox_10->setGeometry(QRect(130, 50, 61, 22));
        spinBox_10->setMaximum(100);
        spinBox_10->setValue(100);
        lblLBIB_RTDVol_3 = new QLabel(fraLeftBIB_3);
        lblLBIB_RTDVol_3->setObjectName(QStringLiteral("lblLBIB_RTDVol_3"));
        lblLBIB_RTDVol_3->setGeometry(QRect(200, 50, 61, 21));
        label_55 = new QLabel(fraLeftBIB_3);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(10, 90, 71, 20));
        label_56 = new QLabel(fraLeftBIB_3);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(10, 110, 91, 20));
        label_56->setFont(font);
        label_57 = new QLabel(fraLeftBIB_3);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(10, 130, 81, 20));
        label_58 = new QLabel(fraLeftBIB_3);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(10, 160, 101, 21));
        cboDefSize_4 = new QComboBox(fraLeftBIB_3);
        cboDefSize_4->setObjectName(QStringLiteral("cboDefSize_4"));
        cboDefSize_4->setGeometry(QRect(130, 160, 71, 22));
        label_59 = new QLabel(fraLeftBIB_3);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(10, 200, 91, 21));
        doubleSpinBox_6 = new QDoubleSpinBox(fraLeftBIB_3);
        doubleSpinBox_6->setObjectName(QStringLiteral("doubleSpinBox_6"));
        doubleSpinBox_6->setGeometry(QRect(130, 200, 71, 22));
        doubleSpinBox_6->setDecimals(1);
        doubleSpinBox_6->setMaximum(20);
        doubleSpinBox_6->setSingleStep(0.5);
        doubleSpinBox_6->setValue(10);
        label_60 = new QLabel(fraLeftBIB_3);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(10, 240, 111, 21));
        spinBox_17 = new QSpinBox(fraLeftBIB_3);
        spinBox_17->setObjectName(QStringLiteral("spinBox_17"));
        spinBox_17->setGeometry(QRect(130, 240, 71, 22));
        label_61 = new QLabel(fraLeftBIB_3);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(10, 260, 111, 21));
        spinBox_18 = new QSpinBox(fraLeftBIB_3);
        spinBox_18->setObjectName(QStringLiteral("spinBox_18"));
        spinBox_18->setGeometry(QRect(130, 260, 71, 22));
        lblLBIBPulsesMild_3 = new QLabel(fraLeftBIB_3);
        lblLBIBPulsesMild_3->setObjectName(QStringLiteral("lblLBIBPulsesMild_3"));
        lblLBIBPulsesMild_3->setGeometry(QRect(200, 90, 121, 21));
        lblLBIBPulsesNormal_3 = new QLabel(fraLeftBIB_3);
        lblLBIBPulsesNormal_3->setObjectName(QStringLiteral("lblLBIBPulsesNormal_3"));
        lblLBIBPulsesNormal_3->setGeometry(QRect(200, 110, 121, 21));
        lblLBIBPulsesNormal_3->setFont(font);
        lblLBIBPulsesStrong_3 = new QLabel(fraLeftBIB_3);
        lblLBIBPulsesStrong_3->setObjectName(QStringLiteral("lblLBIBPulsesStrong_3"));
        lblLBIBPulsesStrong_3->setGeometry(QRect(200, 130, 121, 21));
        label_70 = new QLabel(fraLeftBIB_3);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(130, 10, 181, 21));
        label_70->setFont(font);
        label_71 = new QLabel(fraLeftBIB_3);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(210, 200, 111, 21));
        doubleSpinBox_7 = new QDoubleSpinBox(fraLeftBIB_3);
        doubleSpinBox_7->setObjectName(QStringLiteral("doubleSpinBox_7"));
        doubleSpinBox_7->setGeometry(QRect(130, 90, 62, 22));
        doubleSpinBox_7->setDecimals(0);
        doubleSpinBox_7->setMinimum(50);
        doubleSpinBox_7->setValue(70);
        doubleSpinBox_8 = new QDoubleSpinBox(fraLeftBIB_3);
        doubleSpinBox_8->setObjectName(QStringLiteral("doubleSpinBox_8"));
        doubleSpinBox_8->setGeometry(QRect(130, 110, 62, 22));
        doubleSpinBox_8->setDecimals(0);
        doubleSpinBox_8->setMinimum(50);
        doubleSpinBox_8->setValue(85);
        doubleSpinBox_9 = new QDoubleSpinBox(fraLeftBIB_3);
        doubleSpinBox_9->setObjectName(QStringLiteral("doubleSpinBox_9"));
        doubleSpinBox_9->setGeometry(QRect(130, 130, 62, 22));
        doubleSpinBox_9->setDecimals(0);
        doubleSpinBox_9->setMinimum(50);
        doubleSpinBox_9->setSingleStep(1);
        doubleSpinBox_9->setValue(100);
        spinBox_19 = new QSpinBox(fraLeftBIB_3);
        spinBox_19->setObjectName(QStringLiteral("spinBox_19"));
        spinBox_19->setGeometry(QRect(130, 290, 71, 22));
        spinBox_19->setMinimum(-5000);
        spinBox_19->setMaximum(5000);
        spinBox_19->setSingleStep(100);
        label_69 = new QLabel(fraLeftBIB_3);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(300, 340, 31, 16));
        spinBox_20 = new QSpinBox(fraLeftBIB_3);
        spinBox_20->setObjectName(QStringLiteral("spinBox_20"));
        spinBox_20->setGeometry(QRect(130, 310, 71, 22));
        spinBox_20->setMaximum(9900);
        spinBox_20->setSingleStep(100);
        spinBox_20->setValue(2500);
        label_66 = new QLabel(fraLeftBIB_3);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(10, 310, 101, 16));
        label_65 = new QLabel(fraLeftBIB_3);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(10, 290, 111, 21));
        label_67 = new QLabel(fraLeftBIB_3);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(10, 360, 91, 16));
        label_68 = new QLabel(fraLeftBIB_3);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(120, 340, 61, 16));
        horizontalSlider_6 = new QSlider(fraLeftBIB_3);
        horizontalSlider_6->setObjectName(QStringLiteral("horizontalSlider_6"));
        horizontalSlider_6->setGeometry(QRect(130, 360, 191, 20));
        horizontalSlider_6->setMinimum(40);
        horizontalSlider_6->setMaximum(100);
        horizontalSlider_6->setOrientation(Qt::Horizontal);
        spinBox_21 = new QSpinBox(fraLeftBIB_3);
        spinBox_21->setObjectName(QStringLiteral("spinBox_21"));
        spinBox_21->setGeometry(QRect(130, 410, 71, 22));
        spinBox_21->setMinimum(-5000);
        spinBox_21->setMaximum(5000);
        spinBox_21->setSingleStep(100);
        label_74 = new QLabel(fraLeftBIB_3);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(10, 430, 101, 16));
        label_75 = new QLabel(fraLeftBIB_3);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(10, 410, 111, 21));
        spinBox_22 = new QSpinBox(fraLeftBIB_3);
        spinBox_22->setObjectName(QStringLiteral("spinBox_22"));
        spinBox_22->setGeometry(QRect(130, 430, 71, 22));
        spinBox_22->setMaximum(9900);
        spinBox_22->setSingleStep(100);
        spinBox_22->setValue(2500);
        groupBox = new QGroupBox(dialRecipe);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(1080, 500, 201, 241));
        label_72 = new QLabel(groupBox);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(20, 20, 46, 13));
        comboBox = new QComboBox(groupBox);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(20, 40, 151, 22));
        label_73 = new QLabel(groupBox);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(20, 80, 46, 13));
        comboBox_2 = new QComboBox(groupBox);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setGeometry(QRect(20, 100, 151, 22));
        pushButton = new QPushButton(groupBox);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(60, 150, 75, 61));

        retranslateUi(dialRecipe);
        QObject::connect(buttonBox, SIGNAL(accepted()), dialRecipe, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), dialRecipe, SLOT(reject()));

        QMetaObject::connectSlotsByName(dialRecipe);
    } // setupUi

    void retranslateUi(QDialog *dialRecipe)
    {
        dialRecipe->setWindowTitle(QApplication::translate("dialRecipe", "Dialog", 0));
        grpSteps->setTitle(QApplication::translate("dialRecipe", "Phases", 0));
        label_28->setText(QApplication::translate("dialRecipe", "0", 0));
        label_29->setText(QApplication::translate("dialRecipe", "DA", 0));
        label_30->setText(QApplication::translate("dialRecipe", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">S1<br />Water</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">start</span></p></body></html>", 0));
        label_31->setText(QApplication::translate("dialRecipe", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">S1</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Water<br />stop</span></p></body></html>", 0));
        label_51->setText(QApplication::translate("dialRecipe", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">S1</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"> End</span></p></body></html>", 0));
        label_52->setText(QApplication::translate("dialRecipe", "PT", 0));
        label->setText(QApplication::translate("dialRecipe", "Ingridient type", 0));
        label_10->setText(QApplication::translate("dialRecipe", "Percent of drink", 0));
        spinBox->setSuffix(QApplication::translate("dialRecipe", "%", 0));
        lblLBIB_RTDVol->setText(QApplication::translate("dialRecipe", "125 ml", 0));
        label_12->setText(QApplication::translate("dialRecipe", "Mild Ratio", 0));
        spinBox_2->setPrefix(QApplication::translate("dialRecipe", "1:", 0));
        label_13->setText(QApplication::translate("dialRecipe", "Normal Ratio", 0));
        spinBox_3->setPrefix(QApplication::translate("dialRecipe", "1:", 0));
        label_14->setText(QApplication::translate("dialRecipe", "Strong Ratio", 0));
        spinBox_4->setPrefix(QApplication::translate("dialRecipe", "1:", 0));
        label_15->setText(QApplication::translate("dialRecipe", "Default Strength", 0));
        label_11->setText(QApplication::translate("dialRecipe", "Target flow rate", 0));
        doubleSpinBox->setSuffix(QApplication::translate("dialRecipe", "ml/s", 0));
        label_16->setText(QApplication::translate("dialRecipe", "Ingridient start delay", 0));
        spinBox_5->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        spinBox_5->setPrefix(QString());
        label_17->setText(QApplication::translate("dialRecipe", "Ingridient stop delay", 0));
        spinBox_6->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        lblLBIBPulsesMild->setText(QApplication::translate("dialRecipe", "10 p. + 121 ml w.", 0));
        lblLBIBPulsesNormal->setText(QApplication::translate("dialRecipe", "30 p. + 119 ml w.", 0));
        lblLBIBPulsesStrong->setText(QApplication::translate("dialRecipe", "50 p. + 110 ml w.", 0));
        label_18->setText(QApplication::translate("dialRecipe", "Airvalve", 0));
        label_19->setText(QApplication::translate("dialRecipe", "100% Black", 0));
        label_20->setText(QApplication::translate("dialRecipe", "100% foam", 0));
        label_21->setText(QApplication::translate("dialRecipe", "Airpump start delay", 0));
        spinBox_7->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        spinBox_7->setPrefix(QString());
        label_22->setText(QApplication::translate("dialRecipe", "Airpump runlength", 0));
        spinBox_8->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        label_23->setText(QApplication::translate("dialRecipe", "Airpump speed", 0));
        label_24->setText(QApplication::translate("dialRecipe", "OFF  40%", 0));
        label_25->setText(QApplication::translate("dialRecipe", "100%", 0));
        label_26->setText(QApplication::translate("dialRecipe", "COFFEE", 0));
        label_27->setText(QApplication::translate("dialRecipe", "10,7 Sec disp time", 0));
        lblDeAirTime->setText(QApplication::translate("dialRecipe", "De air Time (DA):", 0));
        lblDeAirTimeValue->setText(QApplication::translate("dialRecipe", "1500 ms", 0));
        label_2->setText(QApplication::translate("dialRecipe", "Preassure time (PT):", 0));
        spPrTime->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        label_3->setText(QApplication::translate("dialRecipe", "RTD Volume Small:", 0));
        spRTDLarge->setSuffix(QApplication::translate("dialRecipe", "ml", 0));
        spRTDLarge_2->setSuffix(QApplication::translate("dialRecipe", "ml", 0));
        label_4->setText(QApplication::translate("dialRecipe", "RTD Volume Medium:", 0));
        spRTDLarge_3->setSuffix(QApplication::translate("dialRecipe", "ml", 0));
        label_5->setText(QApplication::translate("dialRecipe", "RTD Volume Large:", 0));
        label_6->setText(QApplication::translate("dialRecipe", "Sequence 1", 0));
        label_7->setText(QApplication::translate("dialRecipe", "Sequence 2", 0));
        label_8->setText(QApplication::translate("dialRecipe", "Sequence 3", 0));
        label_9->setText(QApplication::translate("dialRecipe", "Default Size", 0));
        btnChange->setText(QApplication::translate("dialRecipe", "Change", 0));
        label_32->setText(QApplication::translate("dialRecipe", "Ingridient type", 0));
        label_33->setText(QApplication::translate("dialRecipe", "Percent of drink", 0));
        spinBox_9->setSuffix(QApplication::translate("dialRecipe", "%", 0));
        lblLBIB_RTDVol_2->setText(QApplication::translate("dialRecipe", "125 ml", 0));
        label_34->setText(QApplication::translate("dialRecipe", "Mild Ratio", 0));
        label_35->setText(QApplication::translate("dialRecipe", "Normal Ratio", 0));
        label_36->setText(QApplication::translate("dialRecipe", "Strong Ratio", 0));
        label_37->setText(QApplication::translate("dialRecipe", "Default Strength", 0));
        label_38->setText(QApplication::translate("dialRecipe", "Target flow rate", 0));
        doubleSpinBox_2->setSuffix(QApplication::translate("dialRecipe", "ml/s", 0));
        label_39->setText(QApplication::translate("dialRecipe", "Ingridient start delay", 0));
        spinBox_13->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        spinBox_13->setPrefix(QString());
        label_40->setText(QApplication::translate("dialRecipe", "Ingridient stop delay", 0));
        spinBox_14->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        lblLBIBPulsesMild_2->setText(QApplication::translate("dialRecipe", "100 p. + 95 ml w.", 0));
        lblLBIBPulsesNormal_2->setText(QApplication::translate("dialRecipe", "300 p. + 75 ml w.", 0));
        lblLBIBPulsesStrong_2->setText(QApplication::translate("dialRecipe", "50 p. + 50 ml w.", 0));
        label_41->setText(QApplication::translate("dialRecipe", "Airvalve", 0));
        label_42->setText(QApplication::translate("dialRecipe", "100% Black", 0));
        label_43->setText(QApplication::translate("dialRecipe", "100% foam", 0));
        label_49->setText(QApplication::translate("dialRecipe", "MILK", 0));
        label_50->setText(QApplication::translate("dialRecipe", "10,7 Sec disp time", 0));
        doubleSpinBox_3->setPrefix(QApplication::translate("dialRecipe", "1:", 0));
        doubleSpinBox_4->setPrefix(QApplication::translate("dialRecipe", "1:", 0));
        doubleSpinBox_5->setPrefix(QApplication::translate("dialRecipe", "1:", 0));
        label_44->setText(QApplication::translate("dialRecipe", "100%", 0));
        label_45->setText(QApplication::translate("dialRecipe", "Airpump runlength", 0));
        label_46->setText(QApplication::translate("dialRecipe", "OFF  40%", 0));
        spinBox_11->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        spinBox_12->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        spinBox_12->setPrefix(QString());
        label_47->setText(QApplication::translate("dialRecipe", "Airpump speed", 0));
        label_48->setText(QApplication::translate("dialRecipe", "Airpump start delay", 0));
        label_53->setText(QApplication::translate("dialRecipe", "Ingridient type", 0));
        label_54->setText(QApplication::translate("dialRecipe", "Percent of drink", 0));
        spinBox_10->setSuffix(QApplication::translate("dialRecipe", "%", 0));
        lblLBIB_RTDVol_3->setText(QApplication::translate("dialRecipe", "125 ml", 0));
        label_55->setText(QApplication::translate("dialRecipe", "Mild speed", 0));
        label_56->setText(QApplication::translate("dialRecipe", "Normal speed", 0));
        label_57->setText(QApplication::translate("dialRecipe", "Strong speed", 0));
        label_58->setText(QApplication::translate("dialRecipe", "Default Strength", 0));
        label_59->setText(QApplication::translate("dialRecipe", "Target flow rate", 0));
        doubleSpinBox_6->setSuffix(QApplication::translate("dialRecipe", "ml/s", 0));
        label_60->setText(QApplication::translate("dialRecipe", "Ingridient start delay", 0));
        spinBox_17->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        spinBox_17->setPrefix(QString());
        label_61->setText(QApplication::translate("dialRecipe", "Ingridient stop delay", 0));
        spinBox_18->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        lblLBIBPulsesMild_3->setText(QApplication::translate("dialRecipe", "100 p. + 95 ml w.", 0));
        lblLBIBPulsesNormal_3->setText(QApplication::translate("dialRecipe", "300 p. + 75 ml w.", 0));
        lblLBIBPulsesStrong_3->setText(QApplication::translate("dialRecipe", "50 p. + 50 ml w.", 0));
        label_70->setText(QApplication::translate("dialRecipe", "INSTANT", 0));
        label_71->setText(QApplication::translate("dialRecipe", "10,7 Sec disp time", 0));
        doubleSpinBox_7->setPrefix(QString());
        doubleSpinBox_7->setSuffix(QApplication::translate("dialRecipe", "%", 0));
        doubleSpinBox_8->setPrefix(QString());
        doubleSpinBox_8->setSuffix(QApplication::translate("dialRecipe", "%", 0));
        doubleSpinBox_9->setPrefix(QString());
        doubleSpinBox_9->setSuffix(QApplication::translate("dialRecipe", "%", 0));
        spinBox_19->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        spinBox_19->setPrefix(QString());
        label_69->setText(QApplication::translate("dialRecipe", "100%", 0));
        spinBox_20->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        label_66->setText(QApplication::translate("dialRecipe", "Mixer stop delay", 0));
        label_65->setText(QApplication::translate("dialRecipe", "Mixer start delay", 0));
        label_67->setText(QApplication::translate("dialRecipe", "Mixer speed", 0));
        label_68->setText(QApplication::translate("dialRecipe", "OFF  40%", 0));
        spinBox_21->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        spinBox_21->setPrefix(QString());
        label_74->setText(QApplication::translate("dialRecipe", "Fan runlength", 0));
        label_75->setText(QApplication::translate("dialRecipe", "Fan start delay", 0));
        spinBox_22->setSuffix(QApplication::translate("dialRecipe", "ms", 0));
        groupBox->setTitle(QApplication::translate("dialRecipe", "Test", 0));
        label_72->setText(QApplication::translate("dialRecipe", "Volume", 0));
        label_73->setText(QApplication::translate("dialRecipe", "Strength", 0));
        pushButton->setText(QApplication::translate("dialRecipe", "Test drink", 0));
    } // retranslateUi

};

namespace Ui {
    class dialRecipe: public Ui_dialRecipe {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_RECIPE_H
